name: Generate influence maps
on:
  workflow_dispatch:
  push:
    branches:
      - add-influence-maps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
      - name: Create conda env and install dependencies
        run: |
          mamba create -y -n mapenv python=3.10 -c conda-forge geopandas matplotlib pyproj pandas shapely fiona rasterio
      - name: Run plot script
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mapenv
          python scripts/plot_influence_maps_both.py
        shell: bash -lc
      - name: Commit generated images back to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output_maps || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add generated influence maps (CI)"
            git push origin HEAD:add-influence-maps
          fi